name: benchmark

#on: [push]
on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    container: archlinux:latest
    timeout-minutes: 30
    steps:
      - name: Update packages
        run: pacman -Syyu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo
      - uses: actions/checkout@v4
      - name: fatal unsafe repository (REPO is owned by someone else)
        run: git config --global --add safe.directory /__w/dotfiles/dotfiles
      - name: Install dotfiles
        run: install_scripts/dotsinstaller.sh install
      - name: Add user
        run: useradd builduser -m
      - name: Add sudoer
        run: echo 'builduser ALL=(ALL) ALL' >> /etc/sudoers
      - name: Change password
        run: passwd -d builduser
      - name: Install arch software
        run: sudo -u builduser bash -c 'install_scripts/arch-extra-setup.sh'
      - name: Install zsh plugins
        run: zsh
        shell: zsh -li --rcs {0}
        env:
          TERM: screen-256color
          ZSHRC_CI_TEST: "true"
      - name: Install neovim plugins
        run: ~/.local/share/zsh/zinit/plugins/neovim---neovim/nvim-linux64/bin/nvim --headless -c 'lua require("lazy").restore({wait = true})' -c 'qall'
      - name: Install packages required benchmark
        run: pacman -S --noconfirm time
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Run benchmark
        run: ./.github/scripts/benchmark.sh
        env:
          TERM: screen-256color
      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: /tmp/result-benchmark.json
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          #benchmark-data-dir-path: .github/pages/dev/bench
          #gh-pages-branch: gh-pages
          # auto-push: true
          comment-on-alert: true
          alert-comment-cc-users: "@yutkat"
          fail-on-alert: false
          alert-threshold: "150%"
      - name: find
        run: find .
      - uses: actions/upload-artifact@v4
        with:
          name: benchmark
          path: ./cache
